#!/usr/bin/env python3
# -*- coding: utf-8 -*-

"""
Tools for working with GPUAMPy calculations on biomolecules (PDB to XYZ).
"""

import os
import pandas as pd


class Biomol:
    """
    Class for storing data from a PDB file.
    """
    def __init__(self, filename):
        self.filename = filename
        self.atoms = []
        self.pdb_data = None
        self.parse()

    # ----------------------------
    # Standard biomolecule sets
    # ----------------------------

    AMINO_ACIDS_PDB = {
        "ALA", "ARG", "ASN", "ASP", "CYS",
        "GLN", "GLU", "GLY", "HIS", "ILE",
        "LEU", "LYS", "MET", "PHE", "PRO",
        "SER", "THR", "TRP", "TYR", "VAL"
    }

    NUCLEOTIDES_PDB = {
        "A", "C", "G", "U", "DA", "DC", "DG", "DT"
    }

    # ----------------------------
    # Element dictionary
    # ----------------------------

    ELEMENT_PDB = {
        "H": "H",   "HE": "He",
        "LI": "Li", "BE": "Be", "B": "B",   "C": "C",   "N": "N",
        "O": "O",   "F": "F",   "NE": "Ne",

        "NA": "Na", "MG": "Mg", "AL": "Al", "SI": "Si", "P": "P",
        "S": "S",   "CL": "Cl", "AR": "Ar",

        "K": "K",   "CA": "Ca"
    }

    # ----------------------------
    # Convert PDB element into chemical element
    # ----------------------------

    def biomolecule_atom_to_element(self, atom_name):
        atom = atom_name.strip().upper()

        if atom == "C" or atom.startswith(("CA", "CB", "CG", "CD", "CE", "CZ", "CH")):
            return "C"

        if atom == "N" or atom.startswith(("ND", "NE", "NH", "NZ")):
            return "N"

        if atom == "O" or atom == "OXT" or atom.startswith(("OD", "OE", "OG", "OH")):
            return "O"

        if atom in ("S", "SD", "SG"):
            return "S"

        if atom == "P":
            return "P"

        if atom == "SE":
            return "Se"

        return None

    # ----------------------------
    # Parse PDB
    # ----------------------------
    
    def parse_atom_line(self, line):

        atom_id = len(self.atoms) + 1

        atom_name = line[12:16].strip()
        residue   = line[17:20].strip()
        chain     = line[21].strip()
        resid     = int(line[22:26])

        x = float(line[30:38])
        y = float(line[38:46])
        z = float(line[46:54])

        element = line[76:78].strip().upper()

        if not element:
            element = self.biomolecule_atom_to_element(atom_name)

        self.atoms.append({
            "atom_id": atom_id,
            "atom_name": atom_name,
            "residue": residue,
            "chain": chain,
            "resid": resid,
            "element": element,
            "x": x,
            "y": y,
            "z": z
        })

    def parse(self):
        found_atom = False

        with open(self.filename, "r") as f:
            for line in f:
                record = line[:6].strip()

                if record in ("ATOM", "HETATM"):
                    found_atom = True
                    self.parse_atom_line(line)

        if not found_atom:
            raise ValueError(
                "Invalid file: could not confirm PDB format. Please ensure the input is a valid PDB file."
            )

        # Convert to DataFrame once parsing is complete
        self.pdb_data = pd.DataFrame(self.atoms)
        
    def get_pdb_data(self):
        return self.pdb_data

    # ----------------------------
    # Export PDB to XYZ
    # ----------------------------

    def to_xyz(self, output_file=None):

        if output_file is None:
            base = os.path.splitext(self.filename)[0]
            output_file = base + ".xyz"

        with open(output_file, "w") as f:

            f.write(f"{len(self.atoms)}\n")
            f.write(f"Generated by GPUAMPy from {self.filename}\n")

            for atom in self.atoms:

                element = atom["element"]

                if element is None:
                    element = self.biomolecule_atom_to_element(atom["atom_name"])

                    if element is None:
                        element = atom["atom_name"][0].upper()

                f.write(
                    f"{element:2s}  "
                    f"{atom['x']: .6f}  "
                    f"{atom['y']: .6f}  "
                    f"{atom['z']: .6f}\n"
                )

        print("XYZ file generated:", output_file)
        
    # ----------------------------
    # Add biosystem info
    # ----------------------------

    def biomol_info(self,
    df,
    interaction_cat="all",
    atom_columns=("atom1_id", "atom2_id")):
        """
        Annotate a DataFrame containing atom IDs with PDB information.
        
        Parameters
        ----------
        df : pandas.DataFrame
            DataFrame containing atom ID columns.
        
        interaction_cat : {"all", "intramolecular", "intermolecular"}, optional
            Filter interactions according to their molecular category.
            Default is "all".
        
        atom_columns : tuple[str], optional
            Columns containing atom IDs.
            Default is ("atom1_id", "atom2_id").
        
        Returns
        -------
        pandas.DataFrame
            Annotated DataFrame.
        """
        
        df = df.copy()
        
        lookup = self.pdb_data.set_index("atom_id")
        
        # ----------------------------
        # Add biomol information
        # ----------------------------
        
        for col in atom_columns:
        
            if col not in df.columns:
                continue
        
            prefix = col.replace("_id", "")
        
            type_col = f"{prefix}_type"
        
            if type_col in df.columns:
                idx = df.columns.get_loc(type_col) + 1
            else:
                idx = df.columns.get_loc(col) + 1
        
            df.insert(idx,     f"{prefix}_residue", df[col].map(lookup["residue"]))
            df.insert(idx + 1, f"{prefix}_resid",   df[col].map(lookup["resid"]))
            df.insert(idx + 2, f"{prefix}_chain",   df[col].map(lookup["chain"]))
        
        # ----------------------------
        # Interaction clasification
        # ----------------------------
        
        biomol = self.AMINO_ACIDS_PDB | self.NUCLEOTIDES_PDB
        
        def classify(res):
            return "prot" if res in biomol else "lig"
        
        bio_interaction = []
        interaction_type = []
        
        for _, row in df.iterrows():
        
            mol1 = classify(row["atom1_residue"])
            mol2 = classify(row["atom2_residue"])
        
            # ---- bio_interaction ----
        
            if mol1 == mol2:
                bio = f"{mol1}-{mol2}"
            else:
                bio = "-".join(sorted([mol1, mol2]))
        
            bio_interaction.append(bio)
        
            # ---- interaction_category ----
        
            if bio == "prot-prot":
                if row["atom1_chain"] == row["atom2_chain"]:
                    interaction_type.append("intramolecular")
                else:
                    interaction_type.append("intermolecular")
        
            elif bio == "lig-lig":
                if (
                    row["atom1_residue"] == row["atom2_residue"]
                    and row["atom1_resid"] == row["atom2_resid"]
                    and row["atom1_chain"] == row["atom2_chain"]
                ):
                    interaction_type.append("intramolecular")
                else:
                    interaction_type.append("intermolecular")
        
            else:
                interaction_type.append("intermolecular")
        
        idx = df.columns.get_loc("interaction_type") + 1
        
        df.insert(idx, "interaction_cat", interaction_type)
        df.insert(idx + 1, "bio_interaction", bio_interaction)
        
        # ----------------------------
        # Interaction category
        # ----------------------------
        
        if interaction_cat == "intramolecular":
            df = df[df["interaction_cat"] == "intramolecular"]
        
        elif interaction_cat == "intermolecular":
            df = df[df["interaction_cat"] == "intermolecular"]
        
        elif interaction_cat != "all":
            raise ValueError(
                "interaction_cat must be 'all', "
                "'intramolecular' or 'intermolecular'."
            )
        
        return df.reset_index(drop=True)
        
    # ----------------------------
    # Add an unrecognized residue
    # ----------------------------   


    def add_residue(self, residue_name, category="protein"):
        """
        Add one or more residues to the recognized biomolecule sets.
        
        Parameters
        ----------
        residue_name : str or list[str]
            Residue name(s), e.g. "MSE" or ["MSE", "SEP", "PTR"].
        category : str, optional
            Biomolecule category. One of {"protein", "nucleotide"}.
            Default is "protein".
            
        Categories
        
        category = protein
        
        category = nucleotide
        
        """
        
        if isinstance(residue_name, str):
            residue_name = [residue_name]
        
        residue_name = [res.upper() for res in residue_name]
        
        if category == "protein":
            self.AMINO_ACIDS_PDB.update(residue_name)
        
        elif category == "nucleotide":
            self.NUCLEOTIDES_PDB.update(residue_name)
        
        else:
            raise ValueError(
                "category must be either 'protein' or 'nucleotide'."
            )
            
